version: '3.8'
services:
  db_auth:
    container_name: db_auth
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: weload
      POSTGRES_USER: postgres
      POSTGRES_DB: crossplatform
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres:13