spring:
  profiles:
    active: dev

  application:
    name: "crossplatform"
    version: "0.1"

  datasource:
    url: jdbc:postgresql://localhost:5432/crossplatform
    username: postgres
    password: weload
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
  
jwt:
    secret: 66f65f5f97904ad05148f5a25c3f24adabf0d0f9b7c5ad09344393a55b8deeef
    access:
        duration:
            minutes: 5
            seconds: 300
        cookie-name: access-token
    refresh:
        duration:
            days: 7
            seconds: 604800
        cookie-name: refresh-token

logging:
  level:
    root: INFO
    com.kfu.crossplatform: DEBUG 
    org.springframework: WARN         
    org.hibernate: INFO
  file:
    name: logs/crossplatform.log      
    max-size: 10MB                     
    max-history: 30                     
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %cyan(%logger{36}) - %level - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %level - %msg%n"

telegram:
  bot:
    token: "8517155444:AAHbXkiILkubCmx9fhDlI-JFQu3SufH6QyU"
    chat-id: "1083065069"